/**
 * Releases page utilities
 *
 * Reads release content from local files generated by scripts/generate-releases.ts
 * Content is generated at build time from CHANGELOG.md with LLM-synthesized notes.
 */

import { readFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";
import type { Release, ReleaseManifest, ReleaseWithNotes } from "@/lib/releases/types";

const CONTENT_DIR = join(process.cwd(), "content/releases");

/**
 * Get all releases with their product notes.
 * Returns releases in descending version order (newest first).
 */
export async function getReleases(): Promise<ReleaseWithNotes[]> {
  const manifestPath = join(CONTENT_DIR, "manifest.json");

  // If no manifest, no releases yet
  if (!existsSync(manifestPath)) {
    return [];
  }

  const manifest: ReleaseManifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
  const releases: ReleaseWithNotes[] = [];

  for (const version of manifest.versions) {
    const releaseDir = join(CONTENT_DIR, `v${version}`);
    const changelogPath = join(releaseDir, "changelog.json");
    const notesPath = join(releaseDir, "notes.md");

    if (!existsSync(changelogPath) || !existsSync(notesPath)) {
      continue;
    }

    const release: Release = JSON.parse(readFileSync(changelogPath, "utf-8"));
    const productNotes = readFileSync(notesPath, "utf-8");

    releases.push({
      ...release,
      productNotes,
    });
  }

  return releases;
}

/**
 * Get a single release by version.
 */
export async function getRelease(version: string): Promise<ReleaseWithNotes | null> {
  // Normalize version (add 'v' prefix if missing)
  const normalizedVersion = version.startsWith("v") ? version.slice(1) : version;
  const releaseDir = join(CONTENT_DIR, `v${normalizedVersion}`);
  const changelogPath = join(releaseDir, "changelog.json");
  const notesPath = join(releaseDir, "notes.md");

  if (!existsSync(changelogPath) || !existsSync(notesPath)) {
    return null;
  }

  const release: Release = JSON.parse(readFileSync(changelogPath, "utf-8"));
  const productNotes = readFileSync(notesPath, "utf-8");

  return {
    ...release,
    productNotes,
  };
}

/**
 * Get the manifest (for version listing, latest version, etc.)
 */
export async function getManifest(): Promise<ReleaseManifest | null> {
  const manifestPath = join(CONTENT_DIR, "manifest.json");

  if (!existsSync(manifestPath)) {
    return null;
  }

  return JSON.parse(readFileSync(manifestPath, "utf-8"));
}

/**
 * Escape CDATA terminators for safe XML embedding
 * Splits ]]> to prevent breaking CDATA sections
 */
export function escapeCdata(text: string): string {
  return text.replace(/]]>/g, "]]]]><![CDATA[>");
}
